name: Build and Test
on: [push]
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Ubuntu GCC
          os: ubuntu-20.04
          cc: gcc-10
          cxx: g++-10
          cmake-generator: Unix Makefiles
        - name: Ubuntu Clang
          os: ubuntu-20.04
          cc: clang-12
          cxx: clang++-12
          cmake-generator: Unix Makefiles
        - name: Windows MSVC
          os: windows-2022
          cmake-generator: Visual Studio 17 2022
        - name: macOS
          os: macos-11
          cmake-generator: Xcode
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
    steps:
      - uses: actions/checkout@v2
      - name: CTest Script
        shell: ctest --extra-verbose --script {0}
        run: |
          cmake_minimum_required(VERSION 3.7)

          site_name(CTEST_SITE)
          set(CTEST_SOURCE_DIRECTORY "$ENV{GITHUB_WORKSPACE}")
          set(CTEST_BINARY_DIRECTORY "$ENV{GITHUB_WORKSPACE}/build")
          set(CTEST_CMAKE_GENERATOR "${{ matrix.config.cmake-generator }}")
          set(CTEST_SUBMIT_URL "https://webhook.site/75d946f8-0b78-4591-a43b-ba3b0d079f4a")

          ctest_start("Experimental")
          ctest_submit(PARTS "Start")

          ctest_configure()
          ctest_submit(PARTS "Configure")

          ctest_build(CONFIGURATION Debug)
          ctest_submit(PARTS "Build")

          ctest_build(CONFIGURATION Release)
          ctest_submit(PARTS "Build")

          ctest_test()
          ctest_submit(PARTS "Test")

          ctest_submit(PARTS "Done")
