name: Build and Test
on: [push]
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest gcc",
            os: ubuntu-latest,
            cc: "gcc-10",
            cxx: "g++-10",
          }
        - {
            name: "Ubuntu Latest clang",
            os: ubuntu-latest,
            cc: "clang-12",
            cxx: "clang++-12",
          }
    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}
    steps:
      - uses: actions/checkout@v2
      - name: CTest Script
        shell: ctest --extra-verbose --script {0}
        run: |
          cmake_minimum_required(VERSION 3.7)

          set(CTEST_SOURCE_DIRECTORY "$ENV{GITHUB_WORKSPACE}")
          set(CTEST_BINARY_DIRECTORY "$ENV{GITHUB_WORKSPACE}/build")
          set(CTEST_CMAKE_GENERATOR "Unix Makefiles")
          set(CTEST_SUBMIT_URL "https://webhook.site/75d946f8-0b78-4591-a43b-ba3b0d079f4a")

          ctest_start("Experimental")
          ctest_configure()
          ctest_build()
          ctest_test()
          ctest_submit()
